# Generated by Django 6.0.2 on 2026-03-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
