# Generated by Django 6.0.3 on 2026-03-04 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_userstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatReadCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=150)),
                ('is_group', models.BooleanField(default=False)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_cursors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'chat_id', 'is_group')},
            },
        ),
    ]
