# Generated by Django 6.0.3 on 2026-03-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_userstatus_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.IntegerField(default=0),
        ),
    ]
