# Generated by Django 6.0.3 on 2026-03-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_message_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='file_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='file_type',
            field=models.CharField(max_length=500),
        ),
    ]
