# Generated by Django 6.0.3 on 2026-03-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_missionroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionroom',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='missionroom',
            name='members',
        ),
        migrations.RemoveField(
            model_name='offlinemessage',
            name='recipient',
        ),
        migrations.AddField(
            model_name='message',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='MissionRoom',
        ),
        migrations.DeleteModel(
            name='OfflineMessage',
        ),
    ]
