# Generated by Django 6.0.3 on 2026-03-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_remove_missionroom_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_emergency_broadcast',
            field=models.BooleanField(default=False),
        ),
    ]
