# Generated by Django 6.0.3 on 2026-04-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_message_is_emergency_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_receipt',
            field=models.IntegerField(default=0),
        ),
    ]
