# Generated by Django 6.0.3 on 2026-04-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_message_read_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='group_receipts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
