# Generated by Django 6.0.3 on 2026-07-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_userpublickey'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='connection_count',
            field=models.IntegerField(default=0),
        ),
    ]
