[pytest]
DJANGO_SETTINGS_MODULE = core.settings
python_files = tests.py test_*.py *_tests.py
addopts = --cov=. --cov-report=html:TEST_SETUP/reports/backend_coverage --cov-report=term
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
