# Generated by Django 6.0.3 on 2026-03-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_muted',
            field=models.BooleanField(default=True),
        ),
    ]
